### ISSUE TITLE
Bazinga 

### ISSUE THREAD

**Issue by GertonsonC** [NewellML/portfolio#2]
That’s right

XOXO
-Sheldon

**Comment by NewellML** [comment]
Stupid dumb face

**Comment by GertonsonC** [comment]
Liam Michael Newell if you don’t respond right now I will tell the robarazzi that you’re into feet and they’ll tell everyone 
![6C5F646C-6692-4ACB-B316-0F91753D32AE](https://user-images.githubusercontent.com/31768160/69161634-14a3f500-0ab1-11ea-8936-cafd0980eb1d.jpeg)

**Comment by NewellML** [comment]
![2764819E-2258-4BC2-A050-825B55F1AEFD](https://user-images.githubusercontent.com/43044186/69161735-39986800-0ab1-11ea-861c-4b41b82383c0.jpeg)
Sheldon Cooper lookin ass
